### ISSUE TITLE
Player exiting from game

### ISSUE THREAD

**Issue by neskimoo** [witnessmenow/Morals-Are-Optional#1]
Need to put in functionality for a player who is currently playing to leave the game if they want to.

**Comment by witnessmenow** [comment]
Should be handled from both Java and Web side

A user should be able to quit themselves and the host should be able to make a user quit

**Comment by witnessmenow** [comment]
Fixed this on the Java side with e658acf2560837ab373aa5ffdf8abcca9c037a5a

**Comment by neskimoo** [comment]
@witnessmenow https://github.com/witnessmenow/Morals-Are-Optional/commit/0d487582947061894a4fff8be6e89b95da436551 fixed as part of this changeset on web
