### ISSUE TITLE
Players who join in the middle of the game see default cards til the next round starts

### ISSUE THREAD

**Issue by witnessmenow** [witnessmenow/Morals-Are-Optional#18]
They see "Card 1" repeated.

They should see "waiting til next round starts message"

**Comment by witnessmenow** [comment]
They now get displayed a message that they will be dealt in the next round

**Comment by neskimoo** [comment]
https://github.com/witnessmenow/Morals-Are-Optional/commit/0d487582947061894a4fff8be6e89b95da436551 is where this was fixed
