### ISSUE TITLE
Won't open on phone

### ISSUE THREAD

**Issue by gillo100** [witnessmenow/Morals-Are-Optional#28]
Hey not really too familiar with github and if this is correct place to put a comment.
I downloaded the apk and installed grand but it won't run. When I try to start it I just get a message to say it has stopped working. Phone is an Xperia Z3 with Android 4.4.4.
I'll keep an eye out for any updates and can try install again and see if it works, I'll also check on a Samsung tablet I have at home this evening and see does it work on that.

**Comment by witnessmenow** [comment]
Hey, this is a perfect place to put the comment! thanks a lot for getting in touch

Maybe there is something wrong with the demo I uploaded last night, not sure if I tested it on android properly. Apologies for that.

I will take a look (hopefully this evening) and let you know.

**Comment by witnessmenow** [comment]
I have uploaded a fixed build up to dropbox now, not sure what was wrong with the last one.

Would you mind confirming its working for you and I'll close this defect out?

Thanks

**Comment by gillo100** [comment]
Downloaded the new one and it starts up grand, will have to get few others
to install so can try have a game and will let you know how it goes

**Comment by witnessmenow** [comment]
Thanks gillo, really sorry about it not working the first time.

Please let us know if you have anymore questions
