### ISSUE TITLE
Some of the text on the cards does not display correct

### ISSUE THREAD

**Issue by witnessmenow** [witnessmenow/Morals-Are-Optional#31]
On the client side:

Hi, this is Jim from accounting. We noticed a $1,200 charge labeled â€�____.â€� Can you explain?

**Comment by nestkimo** [comment]
This may be a problem that strings are escaped by default in the CAHe5 json pack.

**Comment by witnessmenow** [comment]
Another card that does it: Whatever a McRibÂ® is made of
