### ISSUE TITLE
Text on some of the cards on the Host side is not displaying right

### ISSUE THREAD

**Issue by witnessmenow** [witnessmenow/Morals-Are-Optional#35]
registered symbols are showing up as &andR or something

The fonts in libgdx might not support special characters like that, not sure but even if the above was replaced with "(R)" it would look much better

**Comment by nestkimo** [comment]
Tested locally and works fine now with special chars such as &amp; and &reg;

**Comment by witnessmenow** [comment]
Libgdx font does not have special characters such as the TM etc.

I've added some filters to replace those characters with equivalents

**Comment by witnessmenow** [comment]
fixed
